Added Light/Dark Mode Toggles
Arman-ali-khan-786/calculator pull request #39
Opened 2023-10-13 06:21 UTC by LyubomirT

Added a moon (to switch to Dark Mode) / sun (for light mode) button at the navbar, that enables the user to switch between dark / light modes. The base calculator UI has good compatibility with the dark mode already, so I've decided not to do anything with it. Please let me know if you have any questions or concerns!

2023-10-13 07:25 UTC, LyubomirT commented
Some preview:

https://github.com/Arman-ali-khan-786/calculator/assets/127299159/316a5123-393d-4f1e-ab43-e49c09be459c

2023-10-14 16:41 UTC, Arman-ali-khan-786 commented
> Some preview:
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4

add a toggle button in both website as well as in the mobile ui also

2023-10-14 17:55 UTC, LyubomirT commented
> > Some preview:
> > Untitled.video.-.Made.with.Clipchamp.mp4
> 
> add a toggle button in both website as well as in the mobile ui also

Okay! It'll take some time, I'll let you know when I'm done with the update

2023-10-15 06:06 UTC, LyubomirT commented
@Arman-ali-khan-786 Done! Please review the changes and let me know if you have any other questions.

2023-10-15 11:57 UTC, Arman-ali-khan-786 commented
> @Arman-ali-khan-786 Done! Please review the changes and let me know if you have any other questions.

Ui before : 
![Screenshot (674)](https://github.com/Arman-ali-khan-786/calculator/assets/72055054/8c9f263d-27b9-4904-bbce-7ecff25336b3)
![Screenshot (678)](https://github.com/Arman-ali-khan-786/calculator/assets/72055054/685ca10f-3394-4d8c-86f1-d97c7a4da862)

Ui After your changes : 

![Screenshot (675)](https://github.com/Arman-ali-khan-786/calculator/assets/72055054/dce6861f-3985-4363-8f8a-0ceaba0d55b4)
![Screenshot (673)](https://github.com/Arman-ali-khan-786/calculator/assets/72055054/203712e5-f403-4f00-afe1-af25d114f1ef)

Refer to the ss provided above and also take care of the responsiveness of toggle button ok
Another point is that when you change the themes of dark/ light mode : 
   - do consider changes the navbar & font colors also in it and also any hovering effects.
   -  for the mobile ui part do change the color of dialpads and also numbers (effects included)

2023-10-15 11:58 UTC, Arman-ali-khan-786 requested changes
when you change the themes for dark/ light mode :

- do consider changes the navbar & font colors also in it and also any hovering effects.
- for the mobile ui part do change the color of dialpads and also numbers (effects included)

2025-09-03 20:07 UTC, closed without merging